-- prismatic-pink Theme

vim.opt.background = "dark"
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "prismatic-pink"

local function hi(group, opts)
  opts.default = false
  vim.api.nvim_set_hl(0, group, opts)
end

vim.g.terminal_color_0 = "#FFFFFF"
vim.g.terminal_color_1 = "#FF0046"
vim.g.terminal_color_2 = "#2DAE58"
vim.g.terminal_color_3 = "#CF9C00"
vim.g.terminal_color_4 = "#09A1ED"
vim.g.terminal_color_5 = "#C010EF"
vim.g.terminal_color_6 = "#13BBB7"
vim.g.terminal_color_7 = "#22222A"
vim.g.terminal_color_8 = "#666666"
vim.g.terminal_color_9 = "#FF2E87"
vim.g.terminal_color_10 = "#25DA6A"
vim.g.terminal_color_11 = "#FFC104"
vim.g.terminal_color_12 = "#41B9FF"
vim.g.terminal_color_13 = "#C75AF3"
vim.g.terminal_color_14 = "#16DAD6"
vim.g.terminal_color_15 = "#FFFFFF"

hi("Normal", { fg = "#C0C4D0", bg = "#1E1E22" })
hi("NormalNC", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("NormalFloat", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("FloatBorder", { fg = "#3D434F", bg = "#1C1C20" })
hi("FloatTitle", { fg = "#F85EB4", bg = "#1C1C20", bold = true })
hi("Cursor", { fg = "#1E1E22", bg = "#FF1277" })
hi("CursorLine", { bg = "#252529" })
hi("CursorLineNr", { fg = "#FF1277", bold = true })
hi("LineNr", { fg = "#636D83" })
hi("SignColumn", { fg = "#636D83", bg = "#1E1E22" })
hi("ColorColumn", { bg = "#3D434F" })
hi("VertSplit", { fg = "#3D434F" })
hi("WinSeparator", { fg = "#3D434F" })
hi("EndOfBuffer", { fg = "#636D83" })
hi("Folded", { fg = "#828DA0", bg = "#1C1C20" })
hi("FoldColumn", { fg = "#636D83", bg = "#1E1E22" })
hi("StatusLine", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("StatusLineNC", { fg = "#8F9199", bg = "#121218" })
hi("TabLine", { fg = "#8F9199", bg = "#1C1C20" })
hi("TabLineFill", { bg = "#1C1C20" })
hi("TabLineSel", { fg = "#C0C4D0", bg = "#1E1E22", bold = true })
hi("WinBar", { fg = "#7C869B", bg = "#1E1E22" })
hi("WinBarNC", { fg = "#636D83", bg = "#1C1C20" })
hi("Pmenu", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("PmenuSel", { fg = "#C0C4D0", bg = "#2C2C30", bold = true })
hi("PmenuSbar", { bg = "#121218" })
hi("PmenuThumb", { bg = "#828DA0" })
hi("PmenuMatch", { fg = "#F85EB4", bg = "#1C1C20" })
hi("PmenuMatchSel", { fg = "#F85EB4", bg = "#2C2C30", bold = true })
hi("Search", { fg = "#1E1E22", bg = "#9CA320" })
hi("IncSearch", { fg = "#1E1E22", bg = "#FF1277" })
hi("CurSearch", { fg = "#1E1E22", bg = "#FF1277" })
hi("Visual", { bg = "#512535" })
hi("VisualNOS", { bg = "#3b2030" })
hi("MatchParen", { fg = "#FF1277", bold = true })
hi("ModeMsg", { fg = "#3FC56B", bold = true })
hi("MsgArea", { fg = "#C0C4D0" })
hi("MoreMsg", { fg = "#09A1ED" })
hi("Question", { fg = "#09A1ED" })
hi("ErrorMsg", { fg = "#FF1277" })
hi("WarningMsg", { fg = "#E17615" })
hi("DiffAdd", { bg = "#273629" })
hi("DiffChange", { bg = "#213B47" })
hi("DiffDelete", { bg = "#3B1F2C" })
hi("DiffText", { bg = "#213B47" })
hi("Added", { fg = "#31A155" })
hi("Changed", { fg = "#018ACC" })
hi("Removed", { fg = "#FF1277" })
hi("SpellBad", { undercurl = true, sp = "#FF1277" })
hi("SpellCap", { undercurl = true, sp = "#E17615" })
hi("SpellRare", { undercurl = true, sp = "#31A155" })
hi("SpellLocal", { undercurl = true, sp = "#018ACC" })
hi("DiagnosticError", { fg = "#FF1277" })
hi("DiagnosticWarn", { fg = "#E17615" })
hi("DiagnosticInfo", { fg = "#018ACC" })
hi("DiagnosticHint", { fg = "#31A155" })
hi("DiagnosticVirtualTextError", { fg = "#FF1277", bg = "#3E2A3B" })
hi("DiagnosticVirtualTextWarn", { fg = "#E17615", bg = "#403530" })
hi("DiagnosticVirtualTextInfo", { fg = "#018ACC", bg = "#233847" })
hi("DiagnosticVirtualTextHint", { fg = "#31A155", bg = "#293B38" })
hi("DiagnosticUnderlineError", { undercurl = true, sp = "#FF1277" })
hi("DiagnosticUnderlineWarn", { undercurl = true, sp = "#E17615" })
hi("DiagnosticUnderlineInfo", { undercurl = true, sp = "#018ACC" })
hi("DiagnosticUnderlineHint", { undercurl = true, sp = "#31A155" })
hi("DiagnosticSignError", { fg = "#FF1277" })
hi("DiagnosticSignWarn", { fg = "#E17615" })
hi("DiagnosticSignInfo", { fg = "#018ACC" })
hi("DiagnosticSignHint", { fg = "#31A155" })
hi("GitSignsAdd", { fg = "#31A155" })
hi("GitSignsChange", { fg = "#018ACC" })
hi("GitSignsDelete", { fg = "#FF1277" })
hi("Directory", { fg = "#09A1ED" })
hi("Title", { fg = "#F85EB4", bold = true })
hi("NonText", { fg = "#636D83" })
hi("Whitespace", { fg = "#51576C" })
hi("SpecialKey", { fg = "#636D83" })
hi("Conceal", { fg = "#828DA0" })
hi("QuickFixLine", { bg = "#252529" })
hi("qfLineNr", { fg = "#636D83" })
hi("Comment", { fg = "#EEBBFF" })
hi("Constant", { fg = "#FF8D5C" })
hi("String", { fg = "#E3C24A" })
hi("Character", { fg = "#FF8D5C" })
hi("Number", { fg = "#FF8D5C" })
hi("Boolean", { fg = "#FF8D5C" })
hi("Float", { fg = "#FF8D5C" })
hi("Identifier", { fg = "#C0C4D0" })
hi("Function", { fg = "#3FC56B" })
hi("Statement", { fg = "#F85EB4" })
hi("Conditional", { fg = "#F85EB4" })
hi("Repeat", { fg = "#F85EB4" })
hi("Label", { fg = "#89E736" })
hi("Operator", { fg = "#D6FFD6" })
hi("Keyword", { fg = "#F85EB4" })
hi("Exception", { fg = "#F85EB4" })
hi("PreProc", { fg = "#FF2884" })
hi("Include", { fg = "#F85EB4" })
hi("Define", { fg = "#F85EB4" })
hi("Macro", { fg = "#FF2884" })
hi("PreCondit", { fg = "#F85EB4" })
hi("Type", { fg = "#F85EB4" })
hi("StorageClass", { fg = "#F85EB4" })
hi("Structure", { fg = "#10B1FE" })
hi("Typedef", { fg = "#10B1FE" })
hi("Special", { fg = "#FF8D5C" })
hi("SpecialChar", { fg = "#FF8D5C" })
hi("Tag", { fg = "#F85EB4" })
hi("Delimiter", { fg = "#D6FFD6" })
hi("SpecialComment", { fg = "#EEBBFF" })
hi("Debug", { fg = "#F24646" })
hi("Underlined", { underline = true })
hi("Ignore", { fg = "#636D83" })
hi("Error", { fg = "#F24646" })
hi("Todo", { fg = "#C0C4D0", bold = true })
hi("@variable", { fg = "#C0C4D0" })
hi("@variable.builtin", { fg = "#F85EB4" })
hi("@variable.parameter", { fg = "#DD99FF" })
hi("@variable.parameter.builtin", { fg = "#FF8D5C" })
hi("@variable.member", { fg = "#D5C0E9" })
hi("@variable.member.key", { fg = "#D5C0E9" })
hi("@property", { fg = "#D5C0E9" })
hi("@constant", { fg = "#FF8D5C" })
hi("@constant.builtin", { fg = "#FF8D5C" })
hi("@constant.macro", { fg = "#FF8D5C" })
hi("@string", { fg = "#E3C24A" })
hi("@string.escape", { fg = "#FF8D5C" })
hi("@string.special", { fg = "#FF8D5C" })
hi("@string.regexp", { fg = "#FF8D5C" })
hi("@character", { fg = "#FF8D5C" })
hi("@character.special", { fg = "#FF8D5C" })
hi("@number", { fg = "#FF8D5C" })
hi("@number.float", { fg = "#FF8D5C" })
hi("@boolean", { fg = "#FF8D5C" })
hi("@function", { fg = "#3FC56B" })
hi("@function.builtin", { link = "@function" })
hi("@function.call", { link = "@function" })
hi("@function.macro", { fg = "#FF2884" })
hi("@function.method", { link = "@function" })
hi("@function.method.call", { link = "@function" })
hi("@constructor", { fg = "#10B1FE" })
hi("@keyword", { fg = "#F85EB4" })
hi("@keyword.function", { link = "@keyword" })
hi("@keyword.operator", { link = "@keyword" })
hi("@keyword.import", { link = "@keyword" })
hi("@keyword.return", { link = "@keyword" })
hi("@keyword.coroutine", { link = "@keyword" })
hi("@keyword.conditional", { link = "@keyword" })
hi("@keyword.repeat", { link = "@keyword" })
hi("@keyword.exception", { link = "@keyword" })
hi("@keyword.modifier", { link = "@keyword" })
hi("@keyword.type", { link = "@keyword" })
hi("@keyword.debug", { fg = "#F24646" })
hi("@type", { fg = "#10B1FE" })
hi("@type.builtin", { fg = "#F85EB4" })
hi("@type.definition", { fg = "#10B1FE" })
hi("@attribute", { fg = "#FF8D5C" })
hi("@punctuation.delimiter", { fg = "#D6FFD6" })
hi("@punctuation.bracket", { fg = "#D6FFD6" })
hi("@punctuation.special", { fg = "#D6FFD6" })
hi("@operator", { fg = "#D6FFD6" })
hi("@module", { fg = "#C0C4D0" })
hi("@module.builtin", { fg = "#F85EB4" })
hi("@label", { fg = "#89E736" })
hi("@comment", { fg = "#EEBBFF" })
hi("@comment.documentation", { fg = "#EEBBFF" })
hi("@markup.heading", { fg = "#F85EB4", bold = true })
hi("@markup.strong", { fg = "#3FC56B", bold = true })
hi("@markup.italic", { fg = "#EEBBFF", italic = true })
hi("@markup.underline", { underline = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.link", { fg = "#10B1FE", underline = true })
hi("@markup.link.url", { fg = "#8AA5FF", underline = true })
hi("@markup.link.label", { fg = "#09A1ED" })
hi("@markup.raw", { fg = "#C0C4D0" })
hi("@markup.raw.block", { fg = "#C0C4D0" })
hi("@markup.list", { fg = "#15C9C5", bold = true })
hi("@markup.list.checked", { fg = "#15C9C5", bold = true })
hi("@markup.list.unchecked", { fg = "#15C9C5", bold = true })
hi("@markup.quote", { fg = "#E3C24A", italic = true })
hi("@markup.math", { fg = "#FF8D5C" })
hi("@diff.plus", { fg = "#31A155" })
hi("@diff.minus", { fg = "#FF1277" })
hi("@diff.delta", { fg = "#018ACC" })
hi("@tag", { fg = "#F85EB4" })
hi("@tag.builtin", { fg = "#F85EB4" })
hi("@tag.attribute", { fg = "#15C9C5", italic = true })
hi("@tag.delimiter", { fg = "#D6FFD6" })
hi("@lsp.type.namespace", { fg = "#C0C4D0" })
hi("@lsp.type.type", { fg = "#10B1FE" })
hi("@lsp.type.class", { fg = "#10B1FE" })
hi("@lsp.type.struct", { fg = "#10B1FE" })
hi("@lsp.type.enum", { fg = "#10B1FE" })
hi("@lsp.type.interface", { fg = "#8AA5FF" })
hi("@lsp.type.typeParameter", { fg = "#5CA2ED" })
hi("@lsp.type.parameter", { fg = "#DD99FF" })
hi("@lsp.type.variable", { fg = "#C0C4D0" })
hi("@lsp.type.property", { fg = "#D5C0E9" })
hi("@lsp.type.enumMember", { fg = "#15C9C5" })
hi("@lsp.type.function", { fg = "#3FC56B" })
hi("@lsp.type.method", { fg = "#3FC56B" })
hi("@lsp.type.decorator", { fg = "#3FC56B" })
hi("@lsp.type.macro", { fg = "#FF2884" })
hi("@lsp.type.modifier", { fg = "#F85EB4" })
hi("@lsp.type.keyword", { fg = "#F85EB4" })
hi("@lsp.type.operator", { fg = "#D6FFD6" })
hi("@lsp.type.string", { fg = "#E3C24A" })
hi("@lsp.type.number", { fg = "#FF8D5C" })
hi("@lsp.type.regexp", { fg = "#FF8D5C" })
hi("@lsp.type.comment", { fg = "#EEBBFF" })
hi("@lsp.type.event", { fg = "#89E736" })
hi("@lsp.mod.abstract", {  })
hi("@lsp.mod.async", {  })
hi("@lsp.mod.declaration", {  })
hi("@lsp.mod.defaultLibrary", {  })
hi("@lsp.mod.definition", {  })
hi("@lsp.mod.deprecated", {  })
hi("@lsp.mod.documentation", {  })
hi("@lsp.mod.modification", {  })
hi("@lsp.mod.readonly", {  })
hi("@lsp.mod.static", {  })
hi("@lsp.type.builtinType", { fg = "#F85EB4" })
hi("@lsp.type.label", { fg = "#89E736" })
hi("@lsp.type.lifetime", { fg = "#A177F5" })
hi("@lsp.type.selfKeyword", { fg = "#F85EB4" })
hi("@lsp.type.formatSpecifier", { fg = "#A177F5" })
hi("@lsp.mod.mutable", { bold = true })
hi("@lsp.mod.reference", { italic = true })
hi("@lsp.mod.unsafe", { fg = "#F24646" })
hi("TelescopeNormal", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("TelescopeBorder", { fg = "#3D434F", bg = "#1C1C20" })
hi("TelescopePromptNormal", { fg = "#C0C4D0", bg = "#2C2C30" })
hi("TelescopePromptBorder", { fg = "#3D434F", bg = "#2C2C30" })
hi("TelescopePromptTitle", { fg = "#F85EB4", bold = true })
hi("TelescopeResultsTitle", { fg = "#09A1ED", bold = true })
hi("TelescopePreviewTitle", { fg = "#3FC56B", bold = true })
hi("TelescopeSelection", { bg = "#2C2C30" })
hi("TelescopeSelectionCaret", { fg = "#FF1277" })
hi("TelescopeMatching", { fg = "#F85EB4", bold = true })
hi("NvimTreeNormal", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("NvimTreeGitDirty", { fg = "#018ACC" })
hi("NvimTreeGitNew", { fg = "#31A155" })
hi("NvimTreeGitDeleted", { fg = "#FF1277" })
hi("NvimTreeOpenedFile", { fg = "#FF1277" })
hi("NvimTreeRootFolder", { fg = "#F85EB4", bold = true })
hi("NvimTreeFolderIcon", { fg = "#09A1ED" })
hi("NvimTreeFolderName", { fg = "#C0C4D0" })
hi("NvimTreeIndentMarker", { fg = "#3D434F" })
hi("NeoTreeNormal", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("NeoTreeNormalNC", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("NeoTreeRootName", { fg = "#F85EB4", bold = true })
hi("NeoTreeGitAdded", { fg = "#31A155" })
hi("NeoTreeGitModified", { fg = "#018ACC" })
hi("NeoTreeGitDeleted", { fg = "#FF1277" })
hi("NeoTreeGitUntracked", { fg = "#C75AF3" })
hi("WhichKey", { fg = "#F85EB4" })
hi("WhichKeyGroup", { fg = "#09A1ED" })
hi("WhichKeyDesc", { fg = "#C0C4D0" })
hi("WhichKeySeparator", { fg = "#636D83" })
hi("WhichKeyFloat", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("IblIndent", { fg = "#51576C" })
hi("IblScope", { fg = "#FF1277" })
hi("IndentBlanklineChar", { fg = "#51576C" })
hi("IndentBlanklineContextChar", { fg = "#FF1277" })
hi("NotifyERRORBorder", { fg = "#FF1277" })
hi("NotifyWARNBorder", { fg = "#E17615" })
hi("NotifyINFOBorder", { fg = "#018ACC" })
hi("NotifyDEBUGBorder", { fg = "#636D83" })
hi("NotifyTRAcolor.ui.border", { fg = "#A177F5" })
hi("NotifyERRORTitle", { fg = "#FF1277" })
hi("NotifyWARNTitle", { fg = "#E17615" })
hi("NotifyINFOTitle", { fg = "#018ACC" })
hi("NotifyDEBUGTitle", { fg = "#636D83" })
hi("NotifyTRACETitle", { fg = "#A177F5" })
hi("NotifyERRORIcon", { fg = "#FF1277" })
hi("NotifyWARNIcon", { fg = "#E17615" })
hi("NotifyINFOIcon", { fg = "#018ACC" })
hi("lualine_a_normal", { fg = "#1E1E22", bg = "#FF1277", bold = true })
hi("lualine_b_normal", { fg = "#C0C4D0", bg = "#1C1C20" })
hi("lualine_c_normal", { fg = "#8F9199", bg = "#1E1E22" })
